### ISSUE TITLE
Support for other cameras ?

### ISSUE THREAD

**Issue by nonpostrans** [InES-HPMM/FPD-LinkIII_ds90ub95x#11]
Hello! 
Will the driver also support other cams like the Raspi Cam V3?

**Comment by jess-sys** [comment]
Hi,

I am also interested in using this project with a RPi Camera v3.

Is it compatible ? If it’s not, what’s needed to make it work with it ?

Thanks,

—
Jessy

**Comment by MichaelWaespe1** [comment]
Hi,

The Texas Instruments FPD-Link III deserializer/serializer combination is used to transmit MIPI CSI-2 data over long distances via a single coax cable. Additionally an I2C backchannel is supported which works bidirectional. The driver for the FPD-Link III chips works independently of the camera driver. In principle, any camera can be used which is within the specifications of D-PHY v1.2 and CSI-2 v1.3 and which does not exceed the maximum lane speeds of the serializer/deserializer. The parameters in the devicetree may have to be adapted to a different camera. I would recommend checking the data sheets from Texas instruments and comparing them with the Raspi Cam V3.
I do not see any problems that it works with a Raspi Cam V3, but we have not tested it.

Best regards
Michael

**Comment by MichaelWaespe1** [comment]
Hi @nonpostrans @jess-sys 

I have now tested a raspi camera module v3.12. Small changes in the devicetree were necessary because the camera module 3 has a different i2c address than the camera module v2. Additionally there is a DAC which controls the voicecoil for the autofocus whose i2c address also has to be routed through the i2c backchannel of the FPD-Link III chips (also a small change in the devicetree). For these changes I have created a new release which works for the raspi cam v3.12:
[6.1.47-v8+ for Raspi Cam module v3.12](https://github.com/InES-HPMM/FPD-LinkIII_ds90ub95x/releases/tag/raspi-6.1.47-v8%2B_camModuleV3.12)

 In addition, of course, a different camera driver (imx708) must be used. Instructions are new in the readme of this repository:
[README.md](https://github.com/InES-HPMM/FPD-LinkIII_ds90ub95x/blob/master/README.md)

Have fun with it!

Best regards
Michael
