### ISSUE TITLE
Raspiraw on imx219

### ISSUE THREAD

**Issue by shahbazaly** [InES-HPMM/FPD-LinkIII_ds90ub95x#5]
Hello! I was wondering if i can use raspiraw to get raw images from v2 imx219 camera on raspi 4 using this setup of serializer and deserializer? Thank you!

**Comment by JanaUnderground** [comment]
Hi,
I do not have any experience with raspiraw so I just ran raspiraw with the RaspberryPi-FPD-Link setup. The application hangs after the mmal command:

![image](https://user-images.githubusercontent.com/51925599/111436302-1cee5d80-8702-11eb-8bdf-691c2c2012e7.png)

For raw images, you could use v4l-ctl. The following command was tested and a raw frame was successfully captured.
```
v4l2-ctl -d /dev/video0 --set-fmt-video=width=3280,height=2464,pixelformat=RG10  --stream-mmap --stream-count=1 --stream-to=test_3280x2464.bayer
```

**Comment by shahbazaly** [comment]
I had my way out by excluding dtoverlay=imx219 in the config.txt file and adding dtparam=i2c_vc=on. You can try this aswell :)

**Comment by shahbazaly** [comment]
I however have one question. I am trying to use an automobile ECU that connects random sensor to itself and serializes the images using the same chip that you have used in your experiment for the serializer. I want my raspi4 to get images on its MIPI connector from this ECU using the deserializer provided in your experiment. I wonder if I have to write my own driver for the sensors since its not a typical imx219 and hence cannot be detected by raspi4. Any professional suggestions are highly appreciated. Thank you :)

**Comment by JanaUnderground** [comment]
Unfortunately we do need the imx219 overlay. 

Reason:
The GPU of the RaspberryPi has a closed-source unicam driver for the imx219 and when using this the imx219 overlay is not needed anymore because the GPU already has the needed driver. But now the problem that we have is that the GPU unicam driver initialisation runs before or during the fpd-link drivers initialisation. So the unicam driver failes to boot because all communications over fpd-link have to be done after fdp initialisation. So no /dev/video0 camera device is created. That is why we were forced to use the imx219 overlay because now we can just load the imx219 kernel driver with modprobe and the /dev/video0 device is created. The raspiraw program most likey uses GPU functions which fail because the GPU unicam driver is not successfully created.

We will continue trying to solve that issue by somehow delaying the GPU's driver initialisation or finding a way to reload the GPU unicam driver after boot. But at the moment we use libcamera or v4l to get camera data :)


Hmm it is quite difficult to say about the ECU without knowing the which chip is used.

**Comment by shahbazaly** [comment]
Thank you very much :)
